"""remove like_count column

Revision ID: 65e496d0fe3c
Revises: 
Create Date: 2022-10-13 23:15:26.023321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e496d0fe3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'like_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeds', sa.Column('like_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
