"""seeds table, seed_theme column

Revision ID: 77ebdf39109f
Revises: cc58afb83600
Create Date: 2023-01-15 14:38:47.364676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ebdf39109f'
down_revision = 'cc58afb83600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'comments', 'seeds', ['seed_id'], ['id'])
    op.create_foreign_key(None, 'likes', 'seeds', ['seed_id'], ['id'])
    op.add_column('seeds', sa.Column('seed_theme', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeds', 'seed_theme')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    # ### end Alembic commands ###
